[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "usgsxplore"
dynamic = ["version"]
description = "Search and download data or scenes from USGS API"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Godin Luc", email = "godin.luc2002@gmail.com" },
]
maintainers = [
    { name = "Amaury Dehecq", email = "this-is-not-an-email@a.com" },
]
keywords = ["earth observation", "remote sesing", "GIS", "satellite imagery", "USGS", "M2M"]
requires-python = ">=3.9"
dependencies = [
    "requests",
    "geopandas",
    "tqdm",
    "shapely",
    "click",
    "folium",
    "pillow",
    "rasterio"
]

[project.urls]
Homepage = "https://github.com/adehecq/usgs_explorer"
Repository = "https://github.com/adehecq/usgs_explorer"
Documentation = "https://github.com/adehecq/usgs_explorer"

[project.scripts]
usgsxplore = "usgsxplore.cli:cli"

[tool.hatch.version]
source = "vcs"

[tool.hatch.envs.dev]
dependencies = [
    "pytest",
    "pytest-cov",
    "pre-commit",
    "ipykernel",
    "ruff",
    "hatch-vcs",
]

[tool.hatch.envs.dev.scripts]
kernel = "python -m ipykernel install --user --name usgsxplore-dev --display-name 'Python (usgsxplore dev)'"
clean-kernel = "jupyter kernelspec uninstall -y usgsxplore-dev"

[tool.ruff]
line-length = 120
